---
- name: Get rbenv
  git: repo=https://github.com/sstephenson/rbenv.git dest=/usr/local/rbenv

- name: Get ruby-build
  git: repo=https://github.com/sstephenson/ruby-build.git dest=/usr/local/rbenv/plugins/ruby-build

- name: Set rbenv permission
  file: path=/usr/local/rbenv mode=0777 recurse=yes state=directory

- name: Set rbenv env
  copy: src=:etc:profile.d/rbenv.sh dest=/etc/profile.d/rbenv.sh

- name: Is set default ruby version
  shell: "ruby -v | awk -F ' ' '{print $2}' | grep {{ default_ruby_version }}; echo $?"
  register: is_set_default_ruby_version

- name: Install default ruby version
  shell: "rbenv install {{ default_ruby_version }}"
  sudo_user: "{{ ansible_ssh_user }}"
  when: is_set_default_ruby_version is defined and is_set_default_ruby_version != '0'

- name: Set global default ruby version
  shell: "rbenv global {{ default_ruby_version }}"
  sudo_user: "{{ ansible_ssh_user }}"
  when: is_set_default_ruby_version is defined and is_set_default_ruby_version != '0'
