---
- name: get pyenv
  git: repo=https://github.com/yyuu/pyenv.git dest=/usr/local/pyenv

- name: get pyenv-virtualenv
  git: repo=https://github.com/yyuu/pyenv-virtualenv.git dest=/usr/local/pyenv/plugins/pyenv-virtualenv

- name: set pyenv permission
  file: path=/usr/local/pyenv mode=0777 recurse=yes state=directory

- name : set pyenv env
  copy: src=:etc:profile.d/pyenv.sh dest=/etc/profile.d/pyenv.sh
