---
- name: Set mongodb repo
  copy: src=:etc:yum.repos.d/mongodb.repo dest=/etc/yum.repos.d/mongodb.repo

- name: Ensure install mongodb
  yum: name={{ item }} state=installed
  with_items:
    - mongodb-org

- name: Ensure start mongod
  service: name=mongod enabled=yes state=restarted

- name: Set mongodb config
  copy: src=:etc/mongod.conf dest=/etc/mongod.conf
