---
- name: Is phantomjs insatlled
  shell: which phantomjs > /dev/null && phantomjs -v | echo $?
  register: is_phantomjs_insatlled
  ignore_errors: true

- name: Download phantomjs
  get_url: url=https://phantomjs.googlecode.com/files/phantomjs-1.9.0-linux-x86_64.tar.bz2 dest=/tmp/
  when: is_phantomjs_insatlled is defined and is_phantomjs_insatlled.stdout != '0'

- name: tar phantomjs
  shell: tar jxfv /tmp/phantomjs-1.9.0-linux-x86_64.tar.bz2 -C /tmp
  when: is_phantomjs_insatlled is defined and is_phantomjs_insatlled.stdout != '0'

- name: Copy phantomjs
  shell: cp /tmp/phantomjs-1.9.0-linux-x86_64/bin/phantomjs /usr/bin/
  when: is_phantomjs_insatlled is defined and is_phantomjs_insatlled.stdout != '0'
